name: Daily Build and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      MEDIACLOUD_API_TOKEN: ${{ secrets.MEDIACLOUD_API_TOKEN }}
      ACLED_EMAIL: ${{ secrets.ACLED_EMAIL }}
      ACLED_KEY: ${{ secrets.ACLED_KEY }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specific version
          cache: 'pip'
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Install Node.js dependencies
        run: |
          if [ -f package.json ]; then npm install; fi
          
      - name: Run build process
        run: |
          # Run Python data processing scripts
          cd src/data
          for script in polls.json.py rallies.json.py media.json.py tiktok.json.py; do
            echo "Running $script..."
            if ! python "$script"; then
              echo "Error running $script"
              exit 1
            fi
          done
          cd ../..
          
          # Run Observable build if needed
          if [ -f package.json ]; then 
            npm run build || exit 1
          fi
          
      - name: Check build directory
        run: |
          if [ ! -d "./dist" ]; then
            echo "Build directory ./dist does not exist!"
            exit 1
          fi
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this to your build output directory 